name: Get License
description: Get a license
title: "[Lic]: "
labels: ["lic"]
assignees:
  - unattended-ch
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!        
  - type: checkboxes
    id: duration
    attributes:
      label: Duration
      description: Select license duration
      options:
        - label: 1 year = SFr 14.95
        - label: 2 year = SFr 28.95
        - label: 3 year = SFr 38.95
        - label: 5 year = SFr 49.95
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/unattended-ch/ytdlg/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
